# Generated by Django 4.0.3 on 2022-03-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
